/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Portal;

import Datos.DBQuerys;
import javax.swing.JOptionPane;

/**
 *
 * @author Monica
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabelVuelos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        viajes = new javax.swing.JMenu();
        jMenuItemListadoPaises = new javax.swing.JMenuItem();
        jMenuItemListadoCuidades = new javax.swing.JMenuItem();
        jMenuItemListadoRutas = new javax.swing.JMenuItem();
        ListadoDeAviones = new javax.swing.JMenuItem();
        MetodosDePago = new javax.swing.JMenuItem();
        Horarios = new javax.swing.JMenuItem();
        listadoUsuarios = new javax.swing.JMenuItem();
        vuelos = new javax.swing.JMenuItem();
        jMenuItemListadoViajes = new javax.swing.JMenuItem();
        reservas = new javax.swing.JMenuItem();
        jMenuItemReportes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestion de Aerolinea");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabelVuelos.setText("Vuelos de la semana");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        viajes.setText("Ventana");

        jMenuItemListadoPaises.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemListadoPaises.setText("Listado Paises");
        jMenuItemListadoPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoPaisesActionPerformed(evt);
            }
        });
        viajes.add(jMenuItemListadoPaises);

        jMenuItemListadoCuidades.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemListadoCuidades.setText("Listado Ciudades");
        jMenuItemListadoCuidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoCuidadesActionPerformed(evt);
            }
        });
        viajes.add(jMenuItemListadoCuidades);

        jMenuItemListadoRutas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemListadoRutas.setText("Listado Rutas");
        jMenuItemListadoRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoRutasActionPerformed(evt);
            }
        });
        viajes.add(jMenuItemListadoRutas);

        ListadoDeAviones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        ListadoDeAviones.setText("Flota de Aviones");
        ListadoDeAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoDeAvionesActionPerformed(evt);
            }
        });
        viajes.add(ListadoDeAviones);

        MetodosDePago.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        MetodosDePago.setText("Metodos de Pago");
        MetodosDePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetodosDePagoActionPerformed(evt);
            }
        });
        viajes.add(MetodosDePago);

        Horarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        Horarios.setText("Horarios");
        Horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorariosActionPerformed(evt);
            }
        });
        viajes.add(Horarios);

        listadoUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        listadoUsuarios.setText("Listado de usuarios");
        listadoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoUsuariosActionPerformed(evt);
            }
        });
        viajes.add(listadoUsuarios);

        vuelos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        vuelos.setText("Listado de vuelos");
        vuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vuelosActionPerformed(evt);
            }
        });
        viajes.add(vuelos);

        jMenuItemListadoViajes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemListadoViajes.setText("Listado de viajes");
        jMenuItemListadoViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoViajesActionPerformed(evt);
            }
        });
        viajes.add(jMenuItemListadoViajes);

        reservas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        reservas.setText("Listado de reservas");
        reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasActionPerformed(evt);
            }
        });
        viajes.add(reservas);

        jMenuItemReportes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemReportes.setText("Reporte ");
        jMenuItemReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReportesActionPerformed(evt);
            }
        });
        viajes.add(jMenuItemReportes);

        jMenuBar1.add(viajes);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Usuario");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVuelos))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelVuelos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemListadoPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoPaisesActionPerformed
        Presentacion.Presentacion_Pais.listado_paises.View listadoPaises= new Presentacion.Presentacion_Pais.listado_paises.View();
        Presentacion.Presentacion_Pais.listado_paises.Model ModelPaises = new Presentacion.Presentacion_Pais.listado_paises.Model();
        Presentacion.Presentacion_Pais.listado_paises.Controller PaisController = new Presentacion.Presentacion_Pais.listado_paises.Controller(ModelPaises,listadoPaises);        
        listadoPaises.setLocationRelativeTo(null);
        listadoPaises.setVisible(true);
    }//GEN-LAST:event_jMenuItemListadoPaisesActionPerformed

    private void jMenuItemListadoCuidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoCuidadesActionPerformed
        Presentacion.Presentacion_Ciudad.listado_ciudades.View listadoCiudades= new Presentacion.Presentacion_Ciudad.listado_ciudades.View();
        Presentacion.Presentacion_Ciudad.listado_ciudades.Model ModelCiudad = new Presentacion.Presentacion_Ciudad.listado_ciudades.Model();
        Presentacion.Presentacion_Ciudad.listado_ciudades.Controller ciudadController = new Presentacion.Presentacion_Ciudad.listado_ciudades.Controller(ModelCiudad,listadoCiudades);
        listadoCiudades.setLocationRelativeTo(null);
        listadoCiudades.setVisible(true);
    }//GEN-LAST:event_jMenuItemListadoCuidadesActionPerformed

    private void jMenuItemListadoRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoRutasActionPerformed
       Presentacion.Presentacion_Ruta.listado_ruta.Model model = new Presentacion.Presentacion_Ruta.listado_ruta.Model();
       Presentacion.Presentacion_Ruta.listado_ruta.View view= new Presentacion.Presentacion_Ruta.listado_ruta.View();
       Presentacion.Presentacion_Ruta.listado_ruta.Controller controller = new Presentacion.Presentacion_Ruta.listado_ruta.Controller(model, view);       
       view.setLocationRelativeTo(null);
       view.setVisible(true);
       
    }//GEN-LAST:event_jMenuItemListadoRutasActionPerformed

    private void ListadoDeAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoDeAvionesActionPerformed
        Presentacion.Presentacion_Avion.Listado_aviones_disponibles.View ventana = new Presentacion.Presentacion_Avion.Listado_aviones_disponibles.View();
        Presentacion.Presentacion_Avion.Listado_aviones_disponibles.Model modelA = new Presentacion.Presentacion_Avion.Listado_aviones_disponibles.Model();
        Presentacion.Presentacion_Avion.Listado_aviones_disponibles.Controller ControllerA = new Presentacion.Presentacion_Avion.Listado_aviones_disponibles.Controller(modelA,ventana);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);        
    }//GEN-LAST:event_ListadoDeAvionesActionPerformed

    private void MetodosDePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetodosDePagoActionPerformed
        Presentacion.Presentacion_TipoDePago.Listado_De_Pagos.Model listadoModel = new Presentacion.Presentacion_TipoDePago.Listado_De_Pagos.Model();
        Presentacion.Presentacion_TipoDePago.Listado_De_Pagos.View listadoView = new Presentacion.Presentacion_TipoDePago.Listado_De_Pagos.View();
        Presentacion.Presentacion_TipoDePago.Listado_De_Pagos.Controller listadoController = new Presentacion.Presentacion_TipoDePago.Listado_De_Pagos.Controller(listadoModel,listadoView);
        listadoView.setLocationRelativeTo(null);
        listadoView.setVisible(true);        
    }//GEN-LAST:event_MetodosDePagoActionPerformed

    private void HorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorariosActionPerformed
        Presentacion.Presentacion_Horario.listado_horarios.Model model = new  Presentacion.Presentacion_Horario.listado_horarios.Model();
        Presentacion.Presentacion_Horario.listado_horarios.View view = new Presentacion.Presentacion_Horario.listado_horarios.View();
        Presentacion.Presentacion_Horario.listado_horarios.Controller controller = new Presentacion.Presentacion_Horario.listado_horarios.Controller(model, view);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_HorariosActionPerformed

    private void listadoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoUsuariosActionPerformed
        Presentacion.Presentacion_Usuario.Listado_Usuario.View listadoUser = new Presentacion.Presentacion_Usuario.Listado_Usuario.View();
        Presentacion.Presentacion_Usuario.Listado_Usuario.Model modelUser = new Presentacion.Presentacion_Usuario.Listado_Usuario.Model();
        Presentacion.Presentacion_Usuario.Listado_Usuario.Controller controllerUser = new Presentacion.Presentacion_Usuario.Listado_Usuario.Controller(modelUser,listadoUser);
        listadoUser.setLocationRelativeTo(null);
        listadoUser.setVisible(true);           
    }//GEN-LAST:event_listadoUsuariosActionPerformed

    private void vuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vuelosActionPerformed
        Presentacion.Presentacion_Vuelo.Listado_Vuelos_DIsponibles.Model model = new Presentacion.Presentacion_Vuelo.Listado_Vuelos_DIsponibles.Model();
        Presentacion.Presentacion_Vuelo.Listado_Vuelos_DIsponibles.View view = new Presentacion.Presentacion_Vuelo.Listado_Vuelos_DIsponibles.View();
        Presentacion.Presentacion_Vuelo.Listado_Vuelos_DIsponibles.Controller controller = new Presentacion.Presentacion_Vuelo.Listado_Vuelos_DIsponibles.Controller(model, view);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_vuelosActionPerformed

    private void jMenuItemListadoViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoViajesActionPerformed
        Presentacion.Presentacion_Viajes.Listado_Viajes.Model model = new Presentacion.Presentacion_Viajes.Listado_Viajes.Model();
        Presentacion.Presentacion_Viajes.Listado_Viajes.View view = new Presentacion.Presentacion_Viajes.Listado_Viajes.View();
        Presentacion.Presentacion_Viajes.Listado_Viajes.Controller controller = new Presentacion.Presentacion_Viajes.Listado_Viajes.Controller(model, view);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemListadoViajesActionPerformed

    private void reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasActionPerformed
        Presentacion.Presentacion_Reserva.Listado_Reservas.Model model = new Presentacion.Presentacion_Reserva.Listado_Reservas.Model();
        Presentacion.Presentacion_Reserva.Listado_Reservas.View view = new Presentacion.Presentacion_Reserva.Listado_Reservas.View();
        Presentacion.Presentacion_Reserva.Listado_Reservas.Controller controller = new Presentacion.Presentacion_Reserva.Listado_Reservas.Controller(model, view);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_reservasActionPerformed

    private void jMenuItemReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReportesActionPerformed
       DBQuerys db= new DBQuerys();
       try{
           db.db.reporte();
       }catch(Exception se){
           JOptionPane.showMessageDialog(null, "Se generaron errores al cargar el reporte", "Errores Generados",JOptionPane.PLAIN_MESSAGE);
       }
    }//GEN-LAST:event_jMenuItemReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Horarios;
    private javax.swing.JMenuItem ListadoDeAviones;
    private javax.swing.JMenuItem MetodosDePago;
    private javax.swing.JLabel jLabelVuelos;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemListadoCuidades;
    private javax.swing.JMenuItem jMenuItemListadoPaises;
    private javax.swing.JMenuItem jMenuItemListadoRutas;
    private javax.swing.JMenuItem jMenuItemListadoViajes;
    private javax.swing.JMenuItem jMenuItemReportes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem listadoUsuarios;
    private javax.swing.JMenuItem reservas;
    private javax.swing.JMenu viajes;
    private javax.swing.JMenuItem vuelos;
    // End of variables declaration//GEN-END:variables
}
