/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.pagar;

import Datos.DBQuerys;
import Datos.PagoJpaController;
import Datos.ReservaJpaController;
import Datos.TipodePagoJpaController;
import Logica.Pago;
import Logica.TipodePago;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        DBQuerys db= new DBQuerys();
        TipodePagoJpaController tipodepagoDao= new TipodePagoJpaController(db.db.EntityManager);
        List<TipodePago> lista= tipodepagoDao.findTipodePagoEntities();
        for(int i=0;i<lista.size();i++){
            this.jComboBoxPagos.addItem(lista.get(i));
        }
    }

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    public Controller getController() {
        return controller;
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }
    public void CargarPrecio(){
        Integer precio=0;
       
        System.out.println("Viaje: "+this.controller.model.reservaciones.get(0).getViaje().getViaje());
        for(int i=0;i<this.model.reservaciones.size();i++){
           System.out.println("Imprimiendo precio: "+ this.controller.model.reservaciones.get(i).getViaje().getPrecio());
           precio+=model.reservaciones.get(i).getViaje().getPrecio();
       }
       this.jTextFieldMonto.setText(precio.toString());
       this.jTextFieldMonto.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTipodePago = new javax.swing.JLabel();
        jComboBoxPagos = new javax.swing.JComboBox<>();
        jLabelMonto = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldMonto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PAGANDO");

        jLabel1.setText("Pagando");

        jLabelTipodePago.setText("Tipo de pago:");

        jLabelMonto.setText("Monto:");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTipodePago)
                            .addComponent(jLabelMonto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMonto)
                            .addComponent(jComboBoxPagos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButtonAceptar)
                        .addGap(75, 75, 75)
                        .addComponent(jButtonCancelar)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipodePago)
                    .addComponent(jComboBoxPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMonto)
                    .addComponent(jTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
     Pago pago= new Pago();
     pago.setMonto(Double.parseDouble(this.jTextFieldMonto.getText()));
     Date fecha=new Date();
     pago.setFecha(fecha);
     pago.setTipoPagocodigopago((TipodePago) this.jComboBoxPagos.getSelectedItem());
     try{
         PagoJpaController pagoDao= new PagoJpaController(db.db.EntityManager);
         List<Pago> listaDePagos= pagoDao.findPagoEntities();
         Integer numero_de_pago=0;
         if(listaDePagos.isEmpty()){
             numero_de_pago=1;
         }else{
             for(int i=0;i<listaDePagos.size();i++){
             
             if(listaDePagos.get(i).getPago()>numero_de_pago){
                 numero_de_pago=listaDePagos.get(i).getPago();
             }
                }
             numero_de_pago*=2;
         }
        
         
         pago.setPago(numero_de_pago);
         pagoDao.create(pago);
         ReservaJpaController reservaDao= new ReservaJpaController(this.db.db.EntityManager);
         String tiquetes="";
         for(int i=0;i<this.model.reservaciones.size();i++){
             this.model.reservaciones.get(i).setPago(pago);
             reservaDao.create(this.model.reservaciones.get(i));
             tiquetes+=this.model.reservaciones.get(i).imprimeTiquete()+"\n";
             
         }
          JOptionPane.showMessageDialog(null, tiquetes, "Mostrando Tiquetes",JOptionPane.PLAIN_MESSAGE);
          this.dispose();
     }catch(Exception se){
         JOptionPane.showMessageDialog(null, se.getMessage(), "Error al pagar",JOptionPane.PLAIN_MESSAGE);
     }
     
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<TipodePago> jComboBoxPagos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMonto;
    private javax.swing.JLabel jLabelTipodePago;
    private javax.swing.JTextField jTextFieldMonto;
    // End of variables declaration//GEN-END:variables
    public Model model;
    public Controller controller;
    public DBQuerys db= new DBQuerys();
}
